CREATE TABLE IF NOT EXISTS KLANT
( 
	KlantId SMALLINT NOT NULL,
	Voornaam CHAR(24) NOT NULL,
	Tussenvoegsel CHAR(12),
	Achternaam Char(24) NOT NULL,
	Email CHAR(30) NOT NULL ,
	Telefoonnummer CHAR(15) NOT NULL ,
	Straat CHAR(20) NOT NULL ,
	Woonplaats CHAR(20) NOT NULL ,
	Postcode CHAR (7) NOT NULL ,
	BESTELHISTORIE CHAR(50) NOT NULL ,
	PRIMARY KEY(KlantId)
	FOREIGN KEY(BESTLLINGNUMMER)
	REFERENCES BESTELLING(BESTELLINGNUMMER)
)

CREATE TABLE IF NOT EXISTS EIGENAAR
( 
	EIGENAAR SMALLINT NOT NULL,
	NAAM CHAR(24) NOT NULL  ,
	EMAILADRES CHAR(30) NOT NULL ,
	TELEFOONNUMMER CHAR(15) NOT NULL ,
	STRAAT CHAR(20) NOT NULL ,
	WOONPLAATS CHAR(20) NOT NULL ,
	POSTCODE CHAR (7) NOT NULL ,
	BESTELHISTORIE CHAR(50) NOT NULL ,
	PRIMARY KEY(KLANTENNUMMER)
	FOREIGN KEY(BESTLLINGNUMMER)
	REFERENCES BESTELLING(BESTELLINGNUMMER)
)

CREATE TABLE IF NOT EXISTS PRODUCT
(
	PRODUCTNUMMER SMALLINT NOT NULL ,
	PRIJS CHAR(12) NOT NULL ,
	EIGENAARNUMMER SMALLINT NOT NULL ,
	BESTELLINGNUMMER SMALLINT NOT NULL ,
	MODELAUTO CHAR(25) NOT NULL ,
	VERMOGEN CHAR(8) NOT NULL
	PRIMARY KEY(PRODUCTNUMMER) ,
	FOREIGN KEY (BESTELLINGNUMMER)
	REFERECES BESTELLING(BESTELLINGNUMMER) ,
	FOREIGN KEY (EIGENAARNUMMER)
	REFERENCES EIGENAARINFOMATIE(EIGENAARNUMMER)
)

CREATE TABLE IF NOT EXISTS BESTELLING
(
	BESTELLINGNUMMER SMALLINT NOT NULL , 
	KLANTENNUMMER SMALLINT NOT NULL ,
	PRODUCTNUMMER SMALLINT NOT NULL ,
	PRIJS CHAR(12) NOT NULL ,
	EIGENAAR_NUMMER SMALLINT NOT NULL ,
	PRIMARY KEY (BESTELLINGNUMMER) ,
	FOREIGN KEY (KLANTENNUMMER) 
	REFERENCES KLANT(KLATENNUMMER) ,
	FOREIGN KEY (PRODUCTNUMMER) 
	REFERENCES PRODUCT(PRODUCTNUMMER) ,
	FOREIGN KEY (EIGENAARNUMMER)
	REFERENCES EIGENAARINFORMATIE(EIGENAARNMMER)
)
